/* generated */
import Catalog = require('./Catalog');
import CatalogMgr = require('./CatalogMgr');
import Category = require('./Category');
import CategoryAssignment = require('./CategoryAssignment');
import CategoryLink = require('./CategoryLink');
import PriceBook = require('./PriceBook');
import PriceBookMgr = require('./PriceBookMgr');
import Product = require('./Product');
import ProductActiveData = require('./ProductActiveData');
import ProductAttributeModel = require('./ProductAttributeModel');
import ProductAvailabilityLevels = require('./ProductAvailabilityLevels');
import ProductAvailabilityModel = require('./ProductAvailabilityModel');
import ProductInventoryList = require('./ProductInventoryList');
import ProductInventoryMgr = require('./ProductInventoryMgr');
import ProductInventoryRecord = require('./ProductInventoryRecord');
import ProductLink = require('./ProductLink');
import ProductMgr = require('./ProductMgr');
import ProductOption = require('./ProductOption');
import ProductOptionModel = require('./ProductOptionModel');
import ProductOptionValue = require('./ProductOptionValue');
import ProductPriceInfo = require('./ProductPriceInfo');
import ProductPriceModel = require('./ProductPriceModel');
import ProductPriceTable = require('./ProductPriceTable');
import ProductSearchHit = require('./ProductSearchHit');
import ProductSearchModel = require('./ProductSearchModel');
import ProductSearchRefinementDefinition = require('./ProductSearchRefinementDefinition');
import ProductSearchRefinementValue = require('./ProductSearchRefinementValue');
import ProductSearchRefinements = require('./ProductSearchRefinements');
import ProductVariationAttribute = require('./ProductVariationAttribute');
import ProductVariationAttributeValue = require('./ProductVariationAttributeValue');
import ProductVariationModel = require('./ProductVariationModel');
import Recommendation = require('./Recommendation');
import SearchModel = require('./SearchModel');
import SearchRefinementDefinition = require('./SearchRefinementDefinition');
import SearchRefinementValue = require('./SearchRefinementValue');
import SearchRefinements = require('./SearchRefinements');
import SortingOption = require('./SortingOption');
import SortingRule = require('./SortingRule');
import Store = require('./Store');
import StoreGroup = require('./StoreGroup');
import StoreInventoryFilter = require('./StoreInventoryFilter');
import StoreInventoryFilterValue = require('./StoreInventoryFilterValue');
import StoreMgr = require('./StoreMgr');
import Variant = require('./Variant');
import VariationGroup = require('./VariationGroup');


export {Catalog};
export {CatalogMgr};
export {Category};
export {CategoryAssignment};
export {CategoryLink};
export {PriceBook};
export {PriceBookMgr};
export {Product};
export {ProductActiveData};
export {ProductAttributeModel};
export {ProductAvailabilityLevels};
export {ProductAvailabilityModel};
export {ProductInventoryList};
export {ProductInventoryMgr};
export {ProductInventoryRecord};
export {ProductLink};
export {ProductMgr};
export {ProductOption};
export {ProductOptionModel};
export {ProductOptionValue};
export {ProductPriceInfo};
export {ProductPriceModel};
export {ProductPriceTable};
export {ProductSearchHit};
export {ProductSearchModel};
export {ProductSearchRefinementDefinition};
export {ProductSearchRefinementValue};
export {ProductSearchRefinements};
export {ProductVariationAttribute};
export {ProductVariationAttributeValue};
export {ProductVariationModel};
export {Recommendation};
export {SearchModel};
export {SearchRefinementDefinition};
export {SearchRefinementValue};
export {SearchRefinements};
export {SortingOption};
export {SortingRule};
export {Store};
export {StoreGroup};
export {StoreInventoryFilter};
export {StoreInventoryFilterValue};
export {StoreMgr};
export {Variant};
export {VariationGroup}

