'use strict';

/**
 * BaseData - Base class for DTOs
 * Auto-generated by salesforce-data CLI
 */

function BaseData(data) {
    if (data) {
        this._populate(data);
    }
}

BaseData.prototype._populate = function(data) {
    var schema = this.constructor.schema || {};
    var self = this;
    
    Object.keys(schema).forEach(function(key) {
        var config = schema[key];
        var value = data[key];

        if (value !== undefined && value !== null) {
            if (config.transform) {
                self[key] = config.transform(value);
            } else if (config.type === 'collection' && config.of) {
                self[key] = self._transformCollection(value, config.of);
            } else if (config.type === 'data' && config.of) {
                self[key] = new config.of(value);
            } else {
                self[key] = value;
            }
        } else if (config.default !== undefined) {
            self[key] = typeof config.default === 'function' ? config.default() : config.default;
        }
    });
};

BaseData.prototype._transformCollection = function(items, DataClass) {
    if (items && typeof items.iterator === 'function') {
        var result = [];
        var iterator = items.iterator();
        while (iterator.hasNext()) {
            result.push(new DataClass(iterator.next()));
        }
        return result;
    }
    
    if (Array.isArray(items)) {
        return items.map(function(item) {
            return new DataClass(item);
        });
    }
    
    return [];
};

BaseData.prototype.toObject = function() {
    var result = {};
    var schema = this.constructor.schema || {};
    var self = this;

    Object.keys(schema).forEach(function(key) {
        if (self[key] !== undefined) {
            var value = self[key];
            
            if (Array.isArray(value)) {
                result[key] = value.map(function(item) {
                    return item && item.toObject ? item.toObject() : item;
                });
            } else if (value && value.toObject) {
                result[key] = value.toObject();
            } else {
                result[key] = value;
            }
        }
    });

    return result;
};

BaseData.prototype.toJSON = function() {
    return JSON.stringify(this.toObject());
};

BaseData.extend = function(props) {
    var Parent = this;
    var Child = function(data) {
        Parent.call(this, data);
    };
    
    Child.prototype = Object.create(Parent.prototype);
    Child.prototype.constructor = Child;
    
    Object.keys(props).forEach(function(key) {
        Child[key] = props[key];
    });
    
    Child.from = Parent.from;
    Child.collect = Parent.collect;
    Child.optional = Parent.optional;
    Child.extend = Parent.extend;
    
    return Child;
};

BaseData.from = function(data) {
    return new this(data).toObject();
};

BaseData.collect = function(items) {
    var self = this;
    
    if (items && typeof items.iterator === 'function') {
        var result = [];
        var iterator = items.iterator();
        while (iterator.hasNext()) {
            result.push(new self(iterator.next()).toObject());
        }
        return result;
    }

    if (Array.isArray(items)) {
        return items.map(function(item) {
            return new self(item).toObject();
        });
    }

    if (items) {
        return [new self(items).toObject()];
    }

    return [];
};

BaseData.optional = function(data) {
    if (!data || (typeof data === 'object' && Object.keys(data).length === 0)) {
        return null;
    }
    return new this(data).toObject();
};

module.exports = BaseData;